import { Recipe } from "./types";

export const BUILT_IN_RECIPES: Recipe[] = [
  // BREAKFASTS
  {
    id: "r001",
    name: "Greek Yogurt Parfait",
    description: "Creamy Greek yogurt layered with granola, fresh berries, and honey",
    servings: 1,
    prepTime: 5,
    cookTime: 0,
    imageUrl: "https://images.unsplash.com/photo-1488477181946-6428a0291777?w=400",
    tags: ["Vegetarian", "High-Protein", "Gluten-Free"],
    ingredients: [
      { name: "Greek yogurt", amount: 200, unit: "g", category: "Dairy" },
      { name: "Granola", amount: 50, unit: "g", category: "Grains" },
      { name: "Mixed berries", amount: 100, unit: "g", category: "Produce" },
      { name: "Honey", amount: 1, unit: "tbsp", category: "Pantry" },
    ],
    steps: [
      "Add Greek yogurt to a bowl or glass",
      "Layer granola on top",
      "Add fresh mixed berries",
      "Drizzle with honey and serve immediately",
    ],
    nutrition: { calories: 320, protein: 18, carbs: 45, fat: 6 },
  },
  {
    id: "r002",
    name: "Avocado Toast with Eggs",
    description: "Whole grain toast topped with smashed avocado and poached eggs",
    servings: 2,
    prepTime: 10,
    cookTime: 5,
    imageUrl: "https://images.unsplash.com/photo-1541519227354-08fa5d50c820?w=400",
    tags: ["Vegetarian", "High-Protein"],
    ingredients: [
      { name: "Whole grain bread", amount: 4, unit: "slices", category: "Grains" },
      { name: "Avocado", amount: 2, unit: "whole", category: "Produce" },
      { name: "Eggs", amount: 4, unit: "large", category: "Protein" },
      { name: "Lemon juice", amount: 1, unit: "tbsp", category: "Produce" },
      { name: "Red pepper flakes", amount: 0.5, unit: "tsp", category: "Pantry" },
      { name: "Salt", amount: 1, unit: "pinch", category: "Pantry" },
    ],
    steps: [
      "Toast the bread slices",
      "Mash avocado with lemon juice and salt",
      "Poach eggs in simmering water for 3-4 minutes",
      "Spread avocado on toast, top with poached eggs",
      "Sprinkle with red pepper flakes",
    ],
    nutrition: { calories: 420, protein: 22, carbs: 38, fat: 22 },
  },
  {
    id: "r003",
    name: "Overnight Oats",
    description: "No-cook oats soaked overnight with chia seeds and almond milk",
    servings: 1,
    prepTime: 5,
    cookTime: 0,
    imageUrl: "https://images.unsplash.com/photo-1517673408408-c22d4f6a6082?w=400",
    tags: ["Vegetarian", "Vegan", "High-Protein"],
    ingredients: [
      { name: "Rolled oats", amount: 80, unit: "g", category: "Grains" },
      { name: "Almond milk", amount: 200, unit: "ml", category: "Dairy" },
      { name: "Chia seeds", amount: 15, unit: "g", category: "Pantry" },
      { name: "Banana", amount: 1, unit: "medium", category: "Produce" },
      { name: "Peanut butter", amount: 2, unit: "tbsp", category: "Pantry" },
    ],
    steps: [
      "Combine oats, almond milk, and chia seeds in a jar",
      "Stir well, cover, and refrigerate overnight",
      "In the morning, slice banana on top",
      "Drizzle with peanut butter",
    ],
    nutrition: { calories: 450, protein: 16, carbs: 58, fat: 18 },
  },
  {
    id: "r004",
    name: "Spinach & Mushroom Omelette",
    description: "Fluffy egg omelette packed with sautéed spinach and mushrooms",
    servings: 1,
    prepTime: 5,
    cookTime: 8,
    imageUrl: "https://images.unsplash.com/photo-1510693206972-df098062cb71?w=400",
    tags: ["Vegetarian", "Keto", "Gluten-Free", "High-Protein"],
    ingredients: [
      { name: "Eggs", amount: 3, unit: "large", category: "Protein" },
      { name: "Fresh spinach", amount: 60, unit: "g", category: "Produce" },
      { name: "Mushrooms", amount: 80, unit: "g", category: "Produce" },
      { name: "Cheddar cheese", amount: 30, unit: "g", category: "Dairy" },
      { name: "Olive oil", amount: 1, unit: "tbsp", category: "Pantry" },
    ],
    steps: [
      "Sauté mushrooms in olive oil until golden",
      "Add spinach and cook until wilted",
      "Beat eggs with salt and pepper",
      "Pour eggs over the vegetables",
      "Cook until set, fold over, add cheese",
    ],
    nutrition: { calories: 380, protein: 28, carbs: 5, fat: 28 },
  },
  {
    id: "r005",
    name: "Protein Smoothie Bowl",
    description: "Thick açaí-style smoothie bowl topped with seeds, nuts, and fruit",
    servings: 1,
    prepTime: 8,
    cookTime: 0,
    imageUrl: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=400",
    tags: ["Vegetarian", "Vegan", "Gluten-Free", "High-Protein"],
    ingredients: [
      { name: "Frozen mixed berries", amount: 150, unit: "g", category: "Frozen" },
      { name: "Protein powder (vanilla)", amount: 30, unit: "g", category: "Pantry" },
      { name: "Almond milk", amount: 100, unit: "ml", category: "Dairy" },
      { name: "Granola", amount: 40, unit: "g", category: "Grains" },
      { name: "Hemp seeds", amount: 10, unit: "g", category: "Pantry" },
      { name: "Sliced banana", amount: 1, unit: "small", category: "Produce" },
    ],
    steps: [
      "Blend frozen berries, protein powder, and almond milk until thick",
      "Pour into a bowl",
      "Top with granola, hemp seeds, and banana slices",
    ],
    nutrition: { calories: 380, protein: 28, carbs: 50, fat: 8 },
  },
  {
    id: "r006",
    name: "Keto Bacon & Egg Cups",
    description: "Crispy bacon-wrapped egg cups baked in a muffin tin",
    servings: 2,
    prepTime: 5,
    cookTime: 15,
    imageUrl: "https://images.unsplash.com/photo-1525351484163-7529414344d8?w=400",
    tags: ["Keto", "Gluten-Free", "High-Protein"],
    ingredients: [
      { name: "Bacon strips", amount: 6, unit: "strips", category: "Protein" },
      { name: "Eggs", amount: 6, unit: "large", category: "Protein" },
      { name: "Cheddar cheese", amount: 60, unit: "g", category: "Dairy" },
      { name: "Cherry tomatoes", amount: 50, unit: "g", category: "Produce" },
    ],
    steps: [
      "Preheat oven to 200°C (400°F)",
      "Line muffin tin with bacon strips",
      "Crack one egg into each cup",
      "Top with cheese and halved cherry tomatoes",
      "Bake 12-15 minutes until set",
    ],
    nutrition: { calories: 420, protein: 32, carbs: 2, fat: 32 },
  },
  // LUNCHES
  {
    id: "r007",
    name: "Quinoa Buddha Bowl",
    description: "Nourishing bowl with quinoa, roasted veggies, chickpeas, and tahini",
    servings: 2,
    prepTime: 15,
    cookTime: 25,
    imageUrl: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=400",
    tags: ["Vegetarian", "Vegan", "Gluten-Free", "High-Protein"],
    ingredients: [
      { name: "Quinoa", amount: 200, unit: "g", category: "Grains" },
      { name: "Chickpeas (canned)", amount: 400, unit: "g", category: "Protein" },
      { name: "Sweet potato", amount: 300, unit: "g", category: "Produce" },
      { name: "Baby spinach", amount: 100, unit: "g", category: "Produce" },
      { name: "Cherry tomatoes", amount: 150, unit: "g", category: "Produce" },
      { name: "Tahini", amount: 3, unit: "tbsp", category: "Pantry" },
      { name: "Lemon juice", amount: 2, unit: "tbsp", category: "Produce" },
      { name: "Olive oil", amount: 2, unit: "tbsp", category: "Pantry" },
    ],
    steps: [
      "Cook quinoa per package instructions",
      "Roast sweet potato cubes and chickpeas with olive oil at 200°C for 25 min",
      "Whisk tahini with lemon juice and 2 tbsp water for dressing",
      "Assemble bowls with quinoa, roasted veggies, spinach, tomatoes",
      "Drizzle with tahini dressing",
    ],
    nutrition: { calories: 520, protein: 22, carbs: 68, fat: 18 },
  },
  {
    id: "r008",
    name: "Grilled Chicken Caesar Salad",
    description: "Classic Caesar with grilled chicken breast, romaine, parmesan, and croutons",
    servings: 2,
    prepTime: 10,
    cookTime: 15,
    imageUrl: "https://images.unsplash.com/photo-1546793665-c74683f339c1?w=400",
    tags: ["High-Protein", "Gluten-Free"],
    ingredients: [
      { name: "Chicken breast", amount: 400, unit: "g", category: "Protein" },
      { name: "Romaine lettuce", amount: 200, unit: "g", category: "Produce" },
      { name: "Parmesan cheese", amount: 50, unit: "g", category: "Dairy" },
      { name: "Caesar dressing", amount: 4, unit: "tbsp", category: "Pantry" },
      { name: "Croutons", amount: 60, unit: "g", category: "Grains" },
      { name: "Lemon", amount: 1, unit: "whole", category: "Produce" },
    ],
    steps: [
      "Season chicken with salt and pepper",
      "Grill chicken 6-7 min per side until cooked through",
      "Rest chicken, then slice",
      "Toss romaine with Caesar dressing",
      "Top with chicken, parmesan, croutons, and lemon wedge",
    ],
    nutrition: { calories: 490, protein: 48, carbs: 18, fat: 24 },
  },
  {
    id: "r009",
    name: "Turkey & Veggie Wrap",
    description: "Whole wheat wrap with turkey, hummus, cucumber, and mixed greens",
    servings: 1,
    prepTime: 8,
    cookTime: 0,
    imageUrl: "https://images.unsplash.com/photo-1561043433-aaf687c4cf04?w=400",
    tags: ["High-Protein"],
    ingredients: [
      { name: "Whole wheat tortilla", amount: 1, unit: "large", category: "Grains" },
      { name: "Turkey breast slices", amount: 100, unit: "g", category: "Protein" },
      { name: "Hummus", amount: 3, unit: "tbsp", category: "Pantry" },
      { name: "Cucumber", amount: 0.5, unit: "whole", category: "Produce" },
      { name: "Mixed greens", amount: 50, unit: "g", category: "Produce" },
      { name: "Red bell pepper", amount: 0.5, unit: "whole", category: "Produce" },
    ],
    steps: [
      "Spread hummus across the tortilla",
      "Layer turkey breast slices",
      "Add cucumber slices, mixed greens, and bell pepper strips",
      "Roll tightly and cut diagonally",
    ],
    nutrition: { calories: 380, protein: 28, carbs: 42, fat: 10 },
  },
  {
    id: "r010",
    name: "Lentil Soup",
    description: "Hearty red lentil soup with cumin, turmeric, and roasted red peppers",
    servings: 4,
    prepTime: 10,
    cookTime: 30,
    imageUrl: "https://images.unsplash.com/photo-1547592166-23ac45744acd?w=400",
    tags: ["Vegetarian", "Vegan", "Gluten-Free", "High-Protein"],
    ingredients: [
      { name: "Red lentils", amount: 300, unit: "g", category: "Protein" },
      { name: "Vegetable broth", amount: 1000, unit: "ml", category: "Pantry" },
      { name: "Onion", amount: 1, unit: "large", category: "Produce" },
      { name: "Garlic cloves", amount: 4, unit: "whole", category: "Produce" },
      { name: "Roasted red peppers", amount: 200, unit: "g", category: "Produce" },
      { name: "Cumin", amount: 2, unit: "tsp", category: "Pantry" },
      { name: "Turmeric", amount: 1, unit: "tsp", category: "Pantry" },
      { name: "Olive oil", amount: 2, unit: "tbsp", category: "Pantry" },
    ],
    steps: [
      "Sauté onion and garlic in olive oil",
      "Add cumin and turmeric, cook 1 minute",
      "Add lentils, broth, and roasted peppers",
      "Simmer 25-30 minutes until lentils are soft",
      "Blend partially or fully to desired consistency",
    ],
    nutrition: { calories: 280, protein: 18, carbs: 42, fat: 5 },
  },
  {
    id: "r011",
    name: "Tuna Nicoise Salad",
    description: "French-inspired salad with tuna, green beans, eggs, olives, and Dijon vinaigrette",
    servings: 2,
    prepTime: 15,
    cookTime: 10,
    imageUrl: "https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=400",
    tags: ["Gluten-Free", "High-Protein", "Keto"],
    ingredients: [
      { name: "Canned tuna (in water)", amount: 300, unit: "g", category: "Protein" },
      { name: "Green beans", amount: 200, unit: "g", category: "Produce" },
      { name: "Cherry tomatoes", amount: 150, unit: "g", category: "Produce" },
      { name: "Eggs", amount: 4, unit: "large", category: "Protein" },
      { name: "Black olives", amount: 80, unit: "g", category: "Produce" },
      { name: "Dijon mustard", amount: 1, unit: "tbsp", category: "Pantry" },
      { name: "Olive oil", amount: 3, unit: "tbsp", category: "Pantry" },
    ],
    steps: [
      "Hard-boil eggs (8 minutes), peel and halve",
      "Blanch green beans 3-4 minutes, cool in ice water",
      "Whisk Dijon, olive oil, and vinegar for dressing",
      "Arrange all ingredients on plates",
      "Drizzle with dressing",
    ],
    nutrition: { calories: 440, protein: 42, carbs: 12, fat: 24 },
  },
  // DINNERS
  {
    id: "r012",
    name: "Baked Salmon with Asparagus",
    description: "Herb-crusted salmon fillet with roasted asparagus and lemon butter",
    servings: 2,
    prepTime: 10,
    cookTime: 20,
    imageUrl: "https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=400",
    tags: ["Gluten-Free", "Keto", "High-Protein"],
    ingredients: [
      { name: "Salmon fillets", amount: 400, unit: "g", category: "Protein" },
      { name: "Asparagus", amount: 300, unit: "g", category: "Produce" },
      { name: "Butter", amount: 30, unit: "g", category: "Dairy" },
      { name: "Lemon", amount: 1, unit: "whole", category: "Produce" },
      { name: "Garlic cloves", amount: 3, unit: "whole", category: "Produce" },
      { name: "Fresh dill", amount: 10, unit: "g", category: "Produce" },
      { name: "Olive oil", amount: 2, unit: "tbsp", category: "Pantry" },
    ],
    steps: [
      "Preheat oven to 200°C (400°F)",
      "Place salmon and asparagus on a baking sheet",
      "Mix butter, lemon zest, garlic, and dill",
      "Spread over salmon, drizzle asparagus with olive oil",
      "Bake 18-20 minutes",
    ],
    nutrition: { calories: 520, protein: 48, carbs: 8, fat: 32 },
  },
  {
    id: "r013",
    name: "Chicken Stir-Fry",
    description: "Quick and colorful chicken stir-fry with bell peppers, broccoli, and soy-ginger sauce",
    servings: 2,
    prepTime: 15,
    cookTime: 12,
    imageUrl: "https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=400",
    tags: ["High-Protein", "Gluten-Free"],
    ingredients: [
      { name: "Chicken breast", amount: 400, unit: "g", category: "Protein" },
      { name: "Broccoli florets", amount: 200, unit: "g", category: "Produce" },
      { name: "Bell peppers (mixed)", amount: 200, unit: "g", category: "Produce" },
      { name: "Snap peas", amount: 100, unit: "g", category: "Produce" },
      { name: "Soy sauce", amount: 3, unit: "tbsp", category: "Pantry" },
      { name: "Fresh ginger", amount: 20, unit: "g", category: "Produce" },
      { name: "Sesame oil", amount: 1, unit: "tbsp", category: "Pantry" },
      { name: "Brown rice", amount: 200, unit: "g", category: "Grains" },
    ],
    steps: [
      "Cook brown rice per package instructions",
      "Slice chicken into strips and stir-fry in sesame oil 5 minutes",
      "Add vegetables and stir-fry 5 more minutes",
      "Add soy sauce and ginger, cook 2 minutes",
      "Serve over rice",
    ],
    nutrition: { calories: 550, protein: 52, carbs: 52, fat: 12 },
  },
  {
    id: "r014",
    name: "Beef & Broccoli",
    description: "Tender beef strips with broccoli in a rich oyster sauce",
    servings: 4,
    prepTime: 15,
    cookTime: 15,
    imageUrl: "https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=400",
    tags: ["High-Protein", "Gluten-Free"],
    ingredients: [
      { name: "Beef sirloin", amount: 600, unit: "g", category: "Protein" },
      { name: "Broccoli", amount: 400, unit: "g", category: "Produce" },
      { name: "Oyster sauce", amount: 4, unit: "tbsp", category: "Pantry" },
      { name: "Soy sauce", amount: 2, unit: "tbsp", category: "Pantry" },
      { name: "Garlic cloves", amount: 4, unit: "whole", category: "Produce" },
      { name: "Cornstarch", amount: 2, unit: "tbsp", category: "Pantry" },
      { name: "Jasmine rice", amount: 300, unit: "g", category: "Grains" },
    ],
    steps: [
      "Slice beef thin, marinate in soy sauce and cornstarch",
      "Cook rice",
      "Stir-fry beef until seared, set aside",
      "Stir-fry broccoli and garlic 3 minutes",
      "Return beef, add oyster sauce, toss to combine",
    ],
    nutrition: { calories: 480, protein: 42, carbs: 48, fat: 12 },
  },
  {
    id: "r015",
    name: "Vegetable Curry",
    description: "Fragrant coconut milk curry with chickpeas, spinach, and sweet potato",
    servings: 4,
    prepTime: 15,
    cookTime: 30,
    imageUrl: "https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=400",
    tags: ["Vegetarian", "Vegan", "Gluten-Free"],
    ingredients: [
      { name: "Chickpeas (canned)", amount: 400, unit: "g", category: "Protein" },
      { name: "Sweet potato", amount: 400, unit: "g", category: "Produce" },
      { name: "Baby spinach", amount: 100, unit: "g", category: "Produce" },
      { name: "Coconut milk", amount: 400, unit: "ml", category: "Pantry" },
      { name: "Onion", amount: 1, unit: "large", category: "Produce" },
      { name: "Garlic cloves", amount: 4, unit: "whole", category: "Produce" },
      { name: "Curry paste (red)", amount: 3, unit: "tbsp", category: "Pantry" },
      { name: "Basmati rice", amount: 300, unit: "g", category: "Grains" },
    ],
    steps: [
      "Sauté onion and garlic",
      "Add curry paste, cook 2 minutes",
      "Add sweet potato and coconut milk, simmer 15 minutes",
      "Add chickpeas, cook 10 more minutes",
      "Stir in spinach until wilted, serve over basmati rice",
    ],
    nutrition: { calories: 480, protein: 14, carbs: 72, fat: 16 },
  },
  {
    id: "r016",
    name: "Keto Zucchini Noodles with Meatballs",
    description: "Low-carb zucchini noodles topped with homemade beef meatballs and marinara",
    servings: 2,
    prepTime: 20,
    cookTime: 20,
    imageUrl: "https://images.unsplash.com/photo-1555949258-eb67b1ef0ceb?w=400",
    tags: ["Keto", "Gluten-Free", "High-Protein"],
    ingredients: [
      { name: "Zucchini", amount: 4, unit: "medium", category: "Produce" },
      { name: "Ground beef (lean)", amount: 400, unit: "g", category: "Protein" },
      { name: "Egg", amount: 1, unit: "large", category: "Protein" },
      { name: "Parmesan cheese", amount: 50, unit: "g", category: "Dairy" },
      { name: "Marinara sauce (no sugar)", amount: 300, unit: "ml", category: "Pantry" },
      { name: "Italian seasoning", amount: 2, unit: "tsp", category: "Pantry" },
    ],
    steps: [
      "Mix beef, egg, parmesan, and seasoning, form into meatballs",
      "Bake meatballs at 190°C for 18 minutes",
      "Spiralize or peel zucchini into noodles",
      "Sauté zucchini noodles 2-3 minutes",
      "Heat marinara, toss with noodles and top with meatballs",
    ],
    nutrition: { calories: 420, protein: 44, carbs: 18, fat: 20 },
  },
  {
    id: "r017",
    name: "Shrimp Tacos",
    description: "Crispy shrimp with cabbage slaw, avocado, and lime crema in corn tortillas",
    servings: 2,
    prepTime: 15,
    cookTime: 8,
    imageUrl: "https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=400",
    tags: ["Gluten-Free", "High-Protein"],
    ingredients: [
      { name: "Shrimp (peeled)", amount: 300, unit: "g", category: "Protein" },
      { name: "Corn tortillas", amount: 6, unit: "whole", category: "Grains" },
      { name: "Red cabbage", amount: 150, unit: "g", category: "Produce" },
      { name: "Avocado", amount: 1, unit: "whole", category: "Produce" },
      { name: "Sour cream", amount: 4, unit: "tbsp", category: "Dairy" },
      { name: "Lime", amount: 2, unit: "whole", category: "Produce" },
      { name: "Cumin", amount: 1, unit: "tsp", category: "Pantry" },
    ],
    steps: [
      "Season shrimp with cumin, salt, and pepper",
      "Sear shrimp 2-3 min per side until pink",
      "Mix shredded cabbage with lime juice",
      "Mix sour cream with lime zest for crema",
      "Assemble tacos with slaw, shrimp, avocado, and crema",
    ],
    nutrition: { calories: 480, protein: 36, carbs: 40, fat: 18 },
  },
  {
    id: "r018",
    name: "Baked Chicken Thighs",
    description: "Crispy-skinned chicken thighs marinated in garlic herb butter",
    servings: 4,
    prepTime: 10,
    cookTime: 40,
    imageUrl: "https://images.unsplash.com/photo-1598515214211-89d3c73ae83b?w=400",
    tags: ["Keto", "Gluten-Free", "High-Protein"],
    ingredients: [
      { name: "Chicken thighs (bone-in)", amount: 8, unit: "pieces", category: "Protein" },
      { name: "Butter", amount: 60, unit: "g", category: "Dairy" },
      { name: "Garlic cloves", amount: 6, unit: "whole", category: "Produce" },
      { name: "Fresh rosemary", amount: 3, unit: "sprigs", category: "Produce" },
      { name: "Olive oil", amount: 2, unit: "tbsp", category: "Pantry" },
      { name: "Lemon", amount: 1, unit: "whole", category: "Produce" },
    ],
    steps: [
      "Preheat oven to 220°C (425°F)",
      "Mix butter, minced garlic, rosemary, and lemon zest",
      "Loosen chicken skin and push butter under skin",
      "Season outside with oil, salt, and pepper",
      "Roast 38-42 minutes until skin is crispy",
    ],
    nutrition: { calories: 580, protein: 48, carbs: 2, fat: 42 },
  },
  {
    id: "r019",
    name: "Tofu Fried Rice",
    description: "High-protein fried rice with crispy tofu, vegetables, and sesame",
    servings: 2,
    prepTime: 15,
    cookTime: 20,
    imageUrl: "https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=400",
    tags: ["Vegetarian", "Vegan", "High-Protein"],
    ingredients: [
      { name: "Firm tofu", amount: 400, unit: "g", category: "Protein" },
      { name: "Brown rice (cooked)", amount: 400, unit: "g", category: "Grains" },
      { name: "Frozen peas", amount: 100, unit: "g", category: "Frozen" },
      { name: "Carrots", amount: 2, unit: "medium", category: "Produce" },
      { name: "Soy sauce", amount: 3, unit: "tbsp", category: "Pantry" },
      { name: "Sesame oil", amount: 2, unit: "tbsp", category: "Pantry" },
      { name: "Spring onions", amount: 4, unit: "whole", category: "Produce" },
    ],
    steps: [
      "Press tofu dry, cut into cubes",
      "Fry tofu in sesame oil until golden on all sides",
      "Add carrots and peas, cook 3 minutes",
      "Add rice, soy sauce, and stir-fry everything together",
      "Garnish with spring onions",
    ],
    nutrition: { calories: 480, protein: 26, carbs: 58, fat: 16 },
  },
  {
    id: "r020",
    name: "Spaghetti Bolognese",
    description: "Classic Italian meat sauce with slow-cooked vegetables over al dente pasta",
    servings: 4,
    prepTime: 15,
    cookTime: 45,
    imageUrl: "https://images.unsplash.com/photo-1555949258-eb67b1ef0ceb?w=400",
    tags: ["High-Protein"],
    ingredients: [
      { name: "Spaghetti", amount: 400, unit: "g", category: "Grains" },
      { name: "Ground beef (lean)", amount: 500, unit: "g", category: "Protein" },
      { name: "Canned crushed tomatoes", amount: 800, unit: "g", category: "Pantry" },
      { name: "Onion", amount: 1, unit: "large", category: "Produce" },
      { name: "Carrots", amount: 2, unit: "medium", category: "Produce" },
      { name: "Celery", amount: 2, unit: "stalks", category: "Produce" },
      { name: "Red wine", amount: 100, unit: "ml", category: "Beverages" },
      { name: "Parmesan cheese", amount: 80, unit: "g", category: "Dairy" },
    ],
    steps: [
      "Finely dice onion, carrots, and celery (soffritto)",
      "Brown beef, drain excess fat",
      "Add soffritto, cook 10 minutes",
      "Add wine, cook 2 minutes",
      "Add tomatoes, simmer 40 minutes",
      "Cook pasta, serve topped with bolognese and parmesan",
    ],
    nutrition: { calories: 580, protein: 42, carbs: 62, fat: 16 },
  },
  // SNACKS
  {
    id: "r021",
    name: "Apple with Almond Butter",
    description: "Crisp apple slices with creamy almond butter dip",
    servings: 1,
    prepTime: 3,
    cookTime: 0,
    imageUrl: "https://images.unsplash.com/photo-1568702846914-96b305d2aaeb?w=400",
    tags: ["Vegetarian", "Vegan", "Keto", "Gluten-Free"],
    ingredients: [
      { name: "Apple", amount: 1, unit: "medium", category: "Produce" },
      { name: "Almond butter", amount: 2, unit: "tbsp", category: "Pantry" },
    ],
    steps: ["Slice apple", "Serve with almond butter for dipping"],
    nutrition: { calories: 220, protein: 5, carbs: 28, fat: 12 },
  },
  {
    id: "r022",
    name: "Hummus & Veggie Sticks",
    description: "Creamy hummus with a rainbow of fresh vegetable crudités",
    servings: 2,
    prepTime: 10,
    cookTime: 0,
    imageUrl: "https://images.unsplash.com/photo-1615485290382-441e4d049cb5?w=400",
    tags: ["Vegetarian", "Vegan", "Gluten-Free"],
    ingredients: [
      { name: "Hummus", amount: 100, unit: "g", category: "Pantry" },
      { name: "Carrots", amount: 2, unit: "medium", category: "Produce" },
      { name: "Cucumber", amount: 1, unit: "whole", category: "Produce" },
      { name: "Bell pepper", amount: 1, unit: "whole", category: "Produce" },
      { name: "Celery", amount: 3, unit: "stalks", category: "Produce" },
    ],
    steps: [
      "Cut all vegetables into sticks",
      "Serve alongside hummus for dipping",
    ],
    nutrition: { calories: 180, protein: 7, carbs: 22, fat: 7 },
  },
  {
    id: "r023",
    name: "Trail Mix",
    description: "Energy-packed mix of nuts, seeds, dried fruit, and dark chocolate chips",
    servings: 4,
    prepTime: 5,
    cookTime: 0,
    imageUrl: "https://images.unsplash.com/photo-1599599810769-bcde5a160d32?w=400",
    tags: ["Vegetarian", "Vegan", "Gluten-Free", "Keto"],
    ingredients: [
      { name: "Almonds", amount: 60, unit: "g", category: "Pantry" },
      { name: "Walnuts", amount: 60, unit: "g", category: "Pantry" },
      { name: "Pumpkin seeds", amount: 40, unit: "g", category: "Pantry" },
      { name: "Dried cranberries", amount: 40, unit: "g", category: "Pantry" },
      { name: "Dark chocolate chips", amount: 30, unit: "g", category: "Pantry" },
    ],
    steps: ["Combine all ingredients in a bowl", "Divide into portions and store in airtight containers"],
    nutrition: { calories: 280, protein: 9, carbs: 18, fat: 22 },
  },
  {
    id: "r024",
    name: "Cottage Cheese & Fruit",
    description: "High-protein cottage cheese topped with fresh pineapple and mint",
    servings: 1,
    prepTime: 3,
    cookTime: 0,
    imageUrl: "https://images.unsplash.com/photo-1488477181946-6428a0291777?w=400",
    tags: ["Vegetarian", "Gluten-Free", "High-Protein"],
    ingredients: [
      { name: "Cottage cheese", amount: 200, unit: "g", category: "Dairy" },
      { name: "Pineapple chunks", amount: 100, unit: "g", category: "Produce" },
      { name: "Fresh mint", amount: 5, unit: "g", category: "Produce" },
    ],
    steps: ["Spoon cottage cheese into a bowl", "Top with pineapple and mint leaves"],
    nutrition: { calories: 180, protein: 22, carbs: 16, fat: 3 },
  },
  {
    id: "r025",
    name: "Protein Energy Balls",
    description: "No-bake oat protein balls with peanut butter, honey, and chocolate chips",
    servings: 6,
    prepTime: 15,
    cookTime: 0,
    imageUrl: "https://images.unsplash.com/photo-1604329760661-e71dc83f8f26?w=400",
    tags: ["Vegetarian", "High-Protein"],
    ingredients: [
      { name: "Rolled oats", amount: 150, unit: "g", category: "Grains" },
      { name: "Peanut butter", amount: 100, unit: "g", category: "Pantry" },
      { name: "Honey", amount: 3, unit: "tbsp", category: "Pantry" },
      { name: "Protein powder", amount: 30, unit: "g", category: "Pantry" },
      { name: "Dark chocolate chips", amount: 40, unit: "g", category: "Pantry" },
    ],
    steps: [
      "Mix all ingredients in a bowl",
      "Refrigerate 30 minutes to firm up",
      "Roll into 12 balls",
      "Store in fridge for up to 1 week",
    ],
    nutrition: { calories: 220, protein: 12, carbs: 24, fat: 10 },
  },
  // MORE RECIPES to hit 50+
  {
    id: "r026",
    name: "Banana Pancakes",
    description: "Fluffy two-ingredient banana egg pancakes for a naturally sweet breakfast",
    servings: 1,
    prepTime: 5,
    cookTime: 8,
    tags: ["Vegetarian", "Gluten-Free", "High-Protein"],
    ingredients: [
      { name: "Banana", amount: 1, unit: "ripe", category: "Produce" },
      { name: "Eggs", amount: 2, unit: "large", category: "Protein" },
      { name: "Cinnamon", amount: 0.5, unit: "tsp", category: "Pantry" },
    ],
    steps: [
      "Mash banana and mix with beaten eggs and cinnamon",
      "Cook tablespoon-sized pancakes on non-stick pan",
      "Flip when bubbles form, cook 1 more minute",
    ],
    nutrition: { calories: 220, protein: 14, carbs: 28, fat: 8 },
  },
  {
    id: "r027",
    name: "Chia Seed Pudding",
    description: "Thick coconut chia pudding with mango and toasted coconut flakes",
    servings: 2,
    prepTime: 5,
    cookTime: 0,
    tags: ["Vegetarian", "Vegan", "Gluten-Free"],
    ingredients: [
      { name: "Chia seeds", amount: 60, unit: "g", category: "Pantry" },
      { name: "Coconut milk", amount: 400, unit: "ml", category: "Pantry" },
      { name: "Mango", amount: 1, unit: "whole", category: "Produce" },
      { name: "Maple syrup", amount: 2, unit: "tbsp", category: "Pantry" },
      { name: "Coconut flakes", amount: 20, unit: "g", category: "Pantry" },
    ],
    steps: [
      "Mix chia seeds with coconut milk and maple syrup",
      "Refrigerate 4 hours or overnight",
      "Top with diced mango and toasted coconut flakes",
    ],
    nutrition: { calories: 380, protein: 8, carbs: 40, fat: 22 },
  },
  {
    id: "r028",
    name: "Black Bean Tacos",
    description: "Spiced black bean and corn tacos with avocado crema and pico de gallo",
    servings: 2,
    prepTime: 15,
    cookTime: 10,
    tags: ["Vegetarian", "Vegan", "Gluten-Free"],
    ingredients: [
      { name: "Black beans (canned)", amount: 400, unit: "g", category: "Protein" },
      { name: "Corn kernels", amount: 150, unit: "g", category: "Produce" },
      { name: "Corn tortillas", amount: 6, unit: "whole", category: "Grains" },
      { name: "Avocado", amount: 1, unit: "whole", category: "Produce" },
      { name: "Tomatoes", amount: 2, unit: "medium", category: "Produce" },
      { name: "Cilantro", amount: 20, unit: "g", category: "Produce" },
      { name: "Lime", amount: 2, unit: "whole", category: "Produce" },
      { name: "Cumin", amount: 1.5, unit: "tsp", category: "Pantry" },
    ],
    steps: [
      "Season and warm black beans with cumin",
      "Make pico: dice tomatoes, cilantro, onion, lime",
      "Mash avocado with lime for crema",
      "Warm tortillas, fill with beans, corn, pico, and crema",
    ],
    nutrition: { calories: 440, protein: 16, carbs: 68, fat: 14 },
  },
  {
    id: "r029",
    name: "Egg Fried Rice",
    description: "Quick weeknight egg fried rice with peas, carrots, and soy sauce",
    servings: 2,
    prepTime: 5,
    cookTime: 12,
    tags: ["Vegetarian"],
    ingredients: [
      { name: "Cooked white rice", amount: 400, unit: "g", category: "Grains" },
      { name: "Eggs", amount: 3, unit: "large", category: "Protein" },
      { name: "Frozen peas", amount: 100, unit: "g", category: "Frozen" },
      { name: "Carrots", amount: 1, unit: "medium", category: "Produce" },
      { name: "Soy sauce", amount: 3, unit: "tbsp", category: "Pantry" },
      { name: "Vegetable oil", amount: 2, unit: "tbsp", category: "Pantry" },
      { name: "Spring onions", amount: 3, unit: "whole", category: "Produce" },
    ],
    steps: [
      "Stir-fry carrots and peas in oil",
      "Push to side, scramble eggs",
      "Add cold rice and stir-fry 3 minutes",
      "Add soy sauce and spring onions, toss",
    ],
    nutrition: { calories: 440, protein: 18, carbs: 64, fat: 12 },
  },
  {
    id: "r030",
    name: "Pesto Pasta with Cherry Tomatoes",
    description: "Al dente pasta tossed with vibrant basil pesto and roasted cherry tomatoes",
    servings: 2,
    prepTime: 10,
    cookTime: 20,
    tags: ["Vegetarian"],
    ingredients: [
      { name: "Pasta (penne)", amount: 300, unit: "g", category: "Grains" },
      { name: "Cherry tomatoes", amount: 250, unit: "g", category: "Produce" },
      { name: "Basil pesto", amount: 4, unit: "tbsp", category: "Pantry" },
      { name: "Parmesan cheese", amount: 50, unit: "g", category: "Dairy" },
      { name: "Pine nuts", amount: 30, unit: "g", category: "Pantry" },
      { name: "Olive oil", amount: 1, unit: "tbsp", category: "Pantry" },
    ],
    steps: [
      "Roast cherry tomatoes with olive oil 15 minutes",
      "Cook pasta al dente",
      "Drain pasta, reserve 1/2 cup pasta water",
      "Toss pasta with pesto, add pasta water if needed",
      "Top with roasted tomatoes, parmesan, and pine nuts",
    ],
    nutrition: { calories: 620, protein: 22, carbs: 72, fat: 28 },
  },
  {
    id: "r031",
    name: "Cauliflower Fried Rice (Keto)",
    description: "Low-carb cauliflower rice stir-fried with eggs, vegetables, and sesame oil",
    servings: 2,
    prepTime: 10,
    cookTime: 12,
    tags: ["Vegetarian", "Keto", "Gluten-Free"],
    ingredients: [
      { name: "Cauliflower", amount: 600, unit: "g", category: "Produce" },
      { name: "Eggs", amount: 3, unit: "large", category: "Protein" },
      { name: "Frozen peas", amount: 80, unit: "g", category: "Frozen" },
      { name: "Carrots", amount: 1, unit: "medium", category: "Produce" },
      { name: "Soy sauce", amount: 2, unit: "tbsp", category: "Pantry" },
      { name: "Sesame oil", amount: 2, unit: "tbsp", category: "Pantry" },
    ],
    steps: [
      "Rice cauliflower in a food processor",
      "Stir-fry carrots and peas",
      "Add cauliflower rice, cook 5 minutes",
      "Push aside, scramble eggs",
      "Combine, add soy sauce and sesame oil",
    ],
    nutrition: { calories: 280, protein: 18, carbs: 18, fat: 16 },
  },
  {
    id: "r032",
    name: "Garlic Butter Shrimp",
    description: "Succulent shrimp sautéed in garlic herb butter with a splash of white wine",
    servings: 2,
    prepTime: 5,
    cookTime: 8,
    tags: ["Keto", "Gluten-Free", "High-Protein"],
    ingredients: [
      { name: "Shrimp (peeled)", amount: 400, unit: "g", category: "Protein" },
      { name: "Butter", amount: 50, unit: "g", category: "Dairy" },
      { name: "Garlic cloves", amount: 5, unit: "whole", category: "Produce" },
      { name: "White wine", amount: 50, unit: "ml", category: "Beverages" },
      { name: "Fresh parsley", amount: 15, unit: "g", category: "Produce" },
      { name: "Lemon", amount: 1, unit: "whole", category: "Produce" },
    ],
    steps: [
      "Melt butter, sauté minced garlic 1 minute",
      "Add shrimp, cook 2 min per side",
      "Add wine, cook 1 minute",
      "Squeeze lemon, garnish with parsley",
    ],
    nutrition: { calories: 320, protein: 36, carbs: 4, fat: 18 },
  },
  {
    id: "r033",
    name: "Stuffed Bell Peppers",
    description: "Colorful bell peppers stuffed with lean beef, rice, and herbs, baked in tomato sauce",
    servings: 4,
    prepTime: 20,
    cookTime: 40,
    tags: ["Gluten-Free", "High-Protein"],
    ingredients: [
      { name: "Bell peppers (large)", amount: 4, unit: "whole", category: "Produce" },
      { name: "Ground beef (lean)", amount: 400, unit: "g", category: "Protein" },
      { name: "Cooked rice", amount: 200, unit: "g", category: "Grains" },
      { name: "Canned crushed tomatoes", amount: 400, unit: "g", category: "Pantry" },
      { name: "Mozzarella cheese", amount: 100, unit: "g", category: "Dairy" },
      { name: "Onion", amount: 1, unit: "medium", category: "Produce" },
      { name: "Italian seasoning", amount: 2, unit: "tsp", category: "Pantry" },
    ],
    steps: [
      "Cut tops off peppers, remove seeds",
      "Brown beef with onion, season with Italian herbs",
      "Mix with half the tomatoes and rice",
      "Fill peppers, pour remaining tomatoes around peppers",
      "Bake at 190°C for 35 minutes, top with mozzarella last 5 min",
    ],
    nutrition: { calories: 400, protein: 32, carbs: 32, fat: 16 },
  },
  {
    id: "r034",
    name: "Edamame & Brown Rice Bowl",
    description: "Simple nutritious bowl with edamame, brown rice, sesame dressing, and avocado",
    servings: 1,
    prepTime: 5,
    cookTime: 0,
    tags: ["Vegetarian", "Vegan", "Gluten-Free", "High-Protein"],
    ingredients: [
      { name: "Cooked brown rice", amount: 200, unit: "g", category: "Grains" },
      { name: "Shelled edamame", amount: 150, unit: "g", category: "Protein" },
      { name: "Avocado", amount: 0.5, unit: "whole", category: "Produce" },
      { name: "Soy sauce", amount: 1, unit: "tbsp", category: "Pantry" },
      { name: "Sesame oil", amount: 1, unit: "tsp", category: "Pantry" },
      { name: "Sesame seeds", amount: 1, unit: "tbsp", category: "Pantry" },
    ],
    steps: [
      "Place cooked rice in a bowl",
      "Add warmed edamame and sliced avocado",
      "Drizzle with soy sauce and sesame oil",
      "Sprinkle sesame seeds",
    ],
    nutrition: { calories: 480, protein: 22, carbs: 58, fat: 18 },
  },
  {
    id: "r035",
    name: "Mushroom Risotto",
    description: "Creamy Arborio rice with wild mushrooms, white wine, and parmesan",
    servings: 4,
    prepTime: 10,
    cookTime: 35,
    tags: ["Vegetarian", "Gluten-Free"],
    ingredients: [
      { name: "Arborio rice", amount: 320, unit: "g", category: "Grains" },
      { name: "Mixed mushrooms", amount: 400, unit: "g", category: "Produce" },
      { name: "Parmesan cheese", amount: 80, unit: "g", category: "Dairy" },
      { name: "Vegetable broth", amount: 1200, unit: "ml", category: "Pantry" },
      { name: "White wine", amount: 120, unit: "ml", category: "Beverages" },
      { name: "Onion", amount: 1, unit: "medium", category: "Produce" },
      { name: "Butter", amount: 40, unit: "g", category: "Dairy" },
      { name: "Garlic cloves", amount: 3, unit: "whole", category: "Produce" },
    ],
    steps: [
      "Keep broth warm in a separate pan",
      "Sauté onion and garlic in butter",
      "Add rice, toast 2 minutes, add wine",
      "Add broth ladle by ladle, stirring constantly, 25 minutes",
      "Stir in mushrooms (sautéed separately) and parmesan",
    ],
    nutrition: { calories: 480, protein: 14, carbs: 68, fat: 16 },
  },
  {
    id: "r036",
    name: "Tuna Salad Lettuce Cups",
    description: "Light and refreshing tuna salad served in crisp romaine cups",
    servings: 2,
    prepTime: 10,
    cookTime: 0,
    tags: ["Keto", "Gluten-Free", "High-Protein"],
    ingredients: [
      { name: "Canned tuna (in water)", amount: 300, unit: "g", category: "Protein" },
      { name: "Mayonnaise", amount: 3, unit: "tbsp", category: "Pantry" },
      { name: "Celery", amount: 2, unit: "stalks", category: "Produce" },
      { name: "Red onion", amount: 0.25, unit: "whole", category: "Produce" },
      { name: "Romaine lettuce leaves", amount: 8, unit: "large", category: "Produce" },
      { name: "Lemon juice", amount: 1, unit: "tbsp", category: "Produce" },
      { name: "Dijon mustard", amount: 1, unit: "tsp", category: "Pantry" },
    ],
    steps: [
      "Drain tuna, mix with mayo, mustard, and lemon",
      "Add diced celery and red onion",
      "Scoop into romaine lettuce cups",
    ],
    nutrition: { calories: 280, protein: 34, carbs: 4, fat: 14 },
  },
  {
    id: "r037",
    name: "Roasted Veggie & Feta Frittata",
    description: "Baked egg frittata with roasted vegetables and tangy feta cheese",
    servings: 4,
    prepTime: 15,
    cookTime: 30,
    tags: ["Vegetarian", "Keto", "Gluten-Free", "High-Protein"],
    ingredients: [
      { name: "Eggs", amount: 8, unit: "large", category: "Protein" },
      { name: "Feta cheese", amount: 100, unit: "g", category: "Dairy" },
      { name: "Red bell pepper", amount: 1, unit: "whole", category: "Produce" },
      { name: "Zucchini", amount: 1, unit: "medium", category: "Produce" },
      { name: "Cherry tomatoes", amount: 100, unit: "g", category: "Produce" },
      { name: "Olive oil", amount: 2, unit: "tbsp", category: "Pantry" },
      { name: "Fresh basil", amount: 10, unit: "g", category: "Produce" },
    ],
    steps: [
      "Roast diced vegetables at 200°C for 20 minutes",
      "Beat eggs, season well",
      "Scatter vegetables in oven-safe pan, pour eggs over",
      "Crumble feta on top",
      "Bake 20-25 minutes at 180°C until set",
    ],
    nutrition: { calories: 280, protein: 20, carbs: 8, fat: 20 },
  },
  {
    id: "r038",
    name: "Sweet Potato & Black Bean Burrito",
    description: "Hearty vegan burrito with roasted sweet potato, black beans, and chipotle sauce",
    servings: 2,
    prepTime: 15,
    cookTime: 25,
    tags: ["Vegetarian", "Vegan", "High-Protein"],
    ingredients: [
      { name: "Sweet potato", amount: 300, unit: "g", category: "Produce" },
      { name: "Black beans (canned)", amount: 400, unit: "g", category: "Protein" },
      { name: "Whole wheat tortillas", amount: 2, unit: "large", category: "Grains" },
      { name: "Avocado", amount: 1, unit: "whole", category: "Produce" },
      { name: "Chipotle peppers in adobo", amount: 2, unit: "whole", category: "Pantry" },
      { name: "Brown rice", amount: 150, unit: "g", category: "Grains" },
    ],
    steps: [
      "Roast sweet potato cubes with cumin",
      "Cook brown rice",
      "Warm black beans with chipotle",
      "Mash avocado",
      "Assemble burritos and wrap tightly",
    ],
    nutrition: { calories: 620, protein: 22, carbs: 88, fat: 16 },
  },
  {
    id: "r039",
    name: "Caprese Salad",
    description: "Simple elegant salad with fresh mozzarella, heirloom tomatoes, basil, and balsamic",
    servings: 2,
    prepTime: 10,
    cookTime: 0,
    tags: ["Vegetarian", "Keto", "Gluten-Free"],
    ingredients: [
      { name: "Fresh mozzarella", amount: 200, unit: "g", category: "Dairy" },
      { name: "Heirloom tomatoes", amount: 300, unit: "g", category: "Produce" },
      { name: "Fresh basil", amount: 20, unit: "g", category: "Produce" },
      { name: "Extra virgin olive oil", amount: 3, unit: "tbsp", category: "Pantry" },
      { name: "Balsamic glaze", amount: 2, unit: "tbsp", category: "Pantry" },
    ],
    steps: [
      "Slice tomatoes and mozzarella",
      "Alternate on a platter with basil leaves",
      "Drizzle with olive oil and balsamic glaze",
      "Season with flaky salt and pepper",
    ],
    nutrition: { calories: 320, protein: 18, carbs: 8, fat: 24 },
  },
  {
    id: "r040",
    name: "Turkey Meatball Soup",
    description: "Light turkey meatballs in a herb-rich vegetable broth with kale",
    servings: 4,
    prepTime: 20,
    cookTime: 30,
    tags: ["Gluten-Free", "High-Protein"],
    ingredients: [
      { name: "Ground turkey", amount: 500, unit: "g", category: "Protein" },
      { name: "Kale", amount: 200, unit: "g", category: "Produce" },
      { name: "Chicken broth", amount: 1500, unit: "ml", category: "Pantry" },
      { name: "Carrots", amount: 2, unit: "medium", category: "Produce" },
      { name: "Celery", amount: 3, unit: "stalks", category: "Produce" },
      { name: "Cannellini beans", amount: 400, unit: "g", category: "Protein" },
      { name: "Parmesan rind", amount: 1, unit: "piece", category: "Dairy" },
      { name: "Italian seasoning", amount: 2, unit: "tsp", category: "Pantry" },
    ],
    steps: [
      "Form turkey into small meatballs with seasoning",
      "Simmer broth with vegetables 10 minutes",
      "Add meatballs and parmesan rind, simmer 15 minutes",
      "Add beans and kale, cook 5 more minutes",
    ],
    nutrition: { calories: 360, protein: 38, carbs: 26, fat: 12 },
  },
  {
    id: "r041",
    name: "Smashed Cucumber Salad",
    description: "Refreshing Asian-style smashed cucumber salad with sesame and chili",
    servings: 2,
    prepTime: 10,
    cookTime: 0,
    tags: ["Vegetarian", "Vegan", "Keto", "Gluten-Free"],
    ingredients: [
      { name: "Cucumbers", amount: 3, unit: "medium", category: "Produce" },
      { name: "Rice vinegar", amount: 2, unit: "tbsp", category: "Pantry" },
      { name: "Sesame oil", amount: 1, unit: "tbsp", category: "Pantry" },
      { name: "Soy sauce", amount: 1, unit: "tbsp", category: "Pantry" },
      { name: "Chili flakes", amount: 0.5, unit: "tsp", category: "Pantry" },
      { name: "Sesame seeds", amount: 1, unit: "tbsp", category: "Pantry" },
      { name: "Garlic cloves", amount: 2, unit: "whole", category: "Produce" },
    ],
    steps: [
      "Smash cucumbers with the side of a knife, then cut into chunks",
      "Salt and let drain 10 minutes",
      "Whisk vinegar, sesame oil, soy sauce, and chili",
      "Toss cucumbers with dressing and minced garlic",
      "Garnish with sesame seeds",
    ],
    nutrition: { calories: 90, protein: 2, carbs: 8, fat: 6 },
  },
  {
    id: "r042",
    name: "Chicken Tikka Masala",
    description: "Tender chicken in a rich, spiced tomato-cream sauce served with naan",
    servings: 4,
    prepTime: 20,
    cookTime: 35,
    tags: ["High-Protein", "Gluten-Free"],
    ingredients: [
      { name: "Chicken thighs (boneless)", amount: 700, unit: "g", category: "Protein" },
      { name: "Heavy cream", amount: 200, unit: "ml", category: "Dairy" },
      { name: "Canned crushed tomatoes", amount: 400, unit: "g", category: "Pantry" },
      { name: "Onion", amount: 1, unit: "large", category: "Produce" },
      { name: "Garlic cloves", amount: 6, unit: "whole", category: "Produce" },
      { name: "Fresh ginger", amount: 30, unit: "g", category: "Produce" },
      { name: "Garam masala", amount: 2, unit: "tbsp", category: "Pantry" },
      { name: "Basmati rice", amount: 300, unit: "g", category: "Grains" },
    ],
    steps: [
      "Marinate chicken in yogurt and spices 30 min (or overnight)",
      "Sear chicken, set aside",
      "Cook onion, garlic, ginger until soft",
      "Add tomatoes and garam masala, simmer 15 minutes",
      "Add cream and chicken, simmer 10 minutes",
      "Serve over basmati rice",
    ],
    nutrition: { calories: 560, protein: 44, carbs: 48, fat: 22 },
  },
  {
    id: "r043",
    name: "Watermelon Feta Salad",
    description: "Summery salad with watermelon, feta, mint, and balsamic reduction",
    servings: 4,
    prepTime: 10,
    cookTime: 0,
    tags: ["Vegetarian", "Gluten-Free"],
    ingredients: [
      { name: "Watermelon", amount: 800, unit: "g", category: "Produce" },
      { name: "Feta cheese", amount: 150, unit: "g", category: "Dairy" },
      { name: "Fresh mint", amount: 20, unit: "g", category: "Produce" },
      { name: "Balsamic glaze", amount: 3, unit: "tbsp", category: "Pantry" },
      { name: "Arugula", amount: 60, unit: "g", category: "Produce" },
    ],
    steps: [
      "Cut watermelon into cubes",
      "Combine with arugula and torn mint leaves",
      "Crumble feta over top",
      "Drizzle with balsamic glaze",
    ],
    nutrition: { calories: 180, protein: 6, carbs: 24, fat: 8 },
  },
  {
    id: "r044",
    name: "Protein Pancakes",
    description: "Fluffy high-protein pancakes with oat flour and ricotta cheese",
    servings: 2,
    prepTime: 5,
    cookTime: 10,
    tags: ["Vegetarian", "High-Protein"],
    ingredients: [
      { name: "Oat flour", amount: 100, unit: "g", category: "Grains" },
      { name: "Ricotta cheese", amount: 150, unit: "g", category: "Dairy" },
      { name: "Eggs", amount: 2, unit: "large", category: "Protein" },
      { name: "Protein powder (vanilla)", amount: 30, unit: "g", category: "Pantry" },
      { name: "Banana", amount: 1, unit: "medium", category: "Produce" },
      { name: "Maple syrup", amount: 2, unit: "tbsp", category: "Pantry" },
    ],
    steps: [
      "Blend all ingredients until smooth",
      "Cook on medium heat 2-3 min per side",
      "Serve with maple syrup and fresh fruit",
    ],
    nutrition: { calories: 420, protein: 30, carbs: 48, fat: 12 },
  },
  {
    id: "r045",
    name: "Gazpacho",
    description: "Classic chilled Spanish tomato soup — bright, refreshing, and nutritious",
    servings: 4,
    prepTime: 15,
    cookTime: 0,
    tags: ["Vegetarian", "Vegan", "Gluten-Free", "Keto"],
    ingredients: [
      { name: "Ripe tomatoes", amount: 800, unit: "g", category: "Produce" },
      { name: "Cucumber", amount: 1, unit: "whole", category: "Produce" },
      { name: "Red bell pepper", amount: 1, unit: "whole", category: "Produce" },
      { name: "Red onion", amount: 0.5, unit: "whole", category: "Produce" },
      { name: "Extra virgin olive oil", amount: 4, unit: "tbsp", category: "Pantry" },
      { name: "Red wine vinegar", amount: 2, unit: "tbsp", category: "Pantry" },
      { name: "Garlic cloves", amount: 2, unit: "whole", category: "Produce" },
    ],
    steps: [
      "Blend all vegetables until smooth",
      "Add olive oil and vinegar, blend again",
      "Season with salt and pepper",
      "Refrigerate at least 2 hours",
      "Serve cold with olive oil drizzle",
    ],
    nutrition: { calories: 140, protein: 2, carbs: 10, fat: 10 },
  },
  {
    id: "r046",
    name: "Miso Salmon Bowl",
    description: "Miso-glazed salmon over sushi rice with cucumber and pickled ginger",
    servings: 2,
    prepTime: 10,
    cookTime: 15,
    tags: ["Gluten-Free", "High-Protein"],
    ingredients: [
      { name: "Salmon fillets", amount: 400, unit: "g", category: "Protein" },
      { name: "White miso paste", amount: 2, unit: "tbsp", category: "Pantry" },
      { name: "Sushi rice", amount: 300, unit: "g", category: "Grains" },
      { name: "Cucumber", amount: 1, unit: "whole", category: "Produce" },
      { name: "Pickled ginger", amount: 30, unit: "g", category: "Produce" },
      { name: "Sesame seeds", amount: 1, unit: "tbsp", category: "Pantry" },
      { name: "Avocado", amount: 1, unit: "whole", category: "Produce" },
    ],
    steps: [
      "Mix miso with a little water and rice vinegar",
      "Marinate salmon 30 min, grill or broil 12 minutes",
      "Cook sushi rice",
      "Bowl: rice, salmon, sliced cucumber, avocado, pickled ginger",
      "Sprinkle sesame seeds",
    ],
    nutrition: { calories: 580, protein: 46, carbs: 54, fat: 18 },
  },
  {
    id: "r047",
    name: "Spinach & Ricotta Stuffed Shells",
    description: "Jumbo pasta shells filled with ricotta and spinach in marinara sauce",
    servings: 4,
    prepTime: 20,
    cookTime: 35,
    tags: ["Vegetarian"],
    ingredients: [
      { name: "Jumbo pasta shells", amount: 300, unit: "g", category: "Grains" },
      { name: "Ricotta cheese", amount: 500, unit: "g", category: "Dairy" },
      { name: "Fresh spinach", amount: 200, unit: "g", category: "Produce" },
      { name: "Mozzarella cheese", amount: 150, unit: "g", category: "Dairy" },
      { name: "Marinara sauce", amount: 500, unit: "ml", category: "Pantry" },
      { name: "Eggs", amount: 1, unit: "large", category: "Protein" },
      { name: "Italian seasoning", amount: 1, unit: "tsp", category: "Pantry" },
    ],
    steps: [
      "Cook shells until al dente",
      "Mix ricotta, wilted spinach, egg, and seasoning",
      "Fill shells with ricotta mixture",
      "Arrange in baking dish over marinara",
      "Top with mozzarella, bake 30 min at 190°C",
    ],
    nutrition: { calories: 520, protein: 28, carbs: 54, fat: 22 },
  },
  {
    id: "r048",
    name: "Keto Egg Salad",
    description: "Creamy egg salad with mayo, mustard, and dill — perfect on lettuce wraps",
    servings: 2,
    prepTime: 10,
    cookTime: 10,
    tags: ["Vegetarian", "Keto", "Gluten-Free", "High-Protein"],
    ingredients: [
      { name: "Eggs", amount: 6, unit: "large", category: "Protein" },
      { name: "Mayonnaise", amount: 3, unit: "tbsp", category: "Pantry" },
      { name: "Dijon mustard", amount: 1, unit: "tsp", category: "Pantry" },
      { name: "Fresh dill", amount: 10, unit: "g", category: "Produce" },
      { name: "Celery", amount: 2, unit: "stalks", category: "Produce" },
      { name: "Romaine lettuce", amount: 6, unit: "large leaves", category: "Produce" },
    ],
    steps: [
      "Hard-boil eggs 10 minutes, peel and chop",
      "Mix with mayo, mustard, dill, and diced celery",
      "Season to taste",
      "Serve in lettuce leaves",
    ],
    nutrition: { calories: 320, protein: 24, carbs: 4, fat: 24 },
  },
  {
    id: "r049",
    name: "Chickpea Shawarma Bowl",
    description: "Crispy spiced chickpeas over tabbouleh with tzatziki and warm pita",
    servings: 2,
    prepTime: 15,
    cookTime: 25,
    tags: ["Vegetarian", "Vegan", "High-Protein"],
    ingredients: [
      { name: "Chickpeas (canned)", amount: 400, unit: "g", category: "Protein" },
      { name: "Bulgur wheat", amount: 150, unit: "g", category: "Grains" },
      { name: "Cucumber", amount: 1, unit: "whole", category: "Produce" },
      { name: "Cherry tomatoes", amount: 150, unit: "g", category: "Produce" },
      { name: "Fresh parsley", amount: 30, unit: "g", category: "Produce" },
      { name: "Tahini", amount: 3, unit: "tbsp", category: "Pantry" },
      { name: "Shawarma spice blend", amount: 2, unit: "tbsp", category: "Pantry" },
      { name: "Pita bread", amount: 2, unit: "whole", category: "Grains" },
    ],
    steps: [
      "Toss chickpeas with shawarma spice and oil, roast at 200°C 25 minutes",
      "Cook bulgur",
      "Tabbouleh: mix bulgur, diced cucumber, tomatoes, parsley",
      "Thin tahini with lemon juice and water",
      "Assemble bowls, drizzle tahini, serve with pita",
    ],
    nutrition: { calories: 520, protein: 20, carbs: 74, fat: 16 },
  },
  {
    id: "r050",
    name: "Chocolate Protein Smoothie",
    description: "Rich chocolate peanut butter protein smoothie — dessert disguised as fuel",
    servings: 1,
    prepTime: 5,
    cookTime: 0,
    tags: ["Vegetarian", "Gluten-Free", "High-Protein"],
    ingredients: [
      { name: "Frozen banana", amount: 1, unit: "whole", category: "Frozen" },
      { name: "Chocolate protein powder", amount: 30, unit: "g", category: "Pantry" },
      { name: "Peanut butter", amount: 2, unit: "tbsp", category: "Pantry" },
      { name: "Almond milk", amount: 250, unit: "ml", category: "Dairy" },
      { name: "Cocoa powder", amount: 1, unit: "tbsp", category: "Pantry" },
    ],
    steps: [
      "Blend all ingredients until smooth and creamy",
      "Add ice if desired",
      "Serve immediately",
    ],
    nutrition: { calories: 380, protein: 28, carbs: 36, fat: 14 },
  },
  {
    id: "r051",
    name: "Roasted Tomato Soup",
    description: "Silky roasted tomato soup with basil oil and a grilled cheese crouton",
    servings: 4,
    prepTime: 15,
    cookTime: 45,
    tags: ["Vegetarian", "Gluten-Free"],
    ingredients: [
      { name: "Ripe tomatoes", amount: 1000, unit: "g", category: "Produce" },
      { name: "Onion", amount: 1, unit: "large", category: "Produce" },
      { name: "Garlic cloves", amount: 6, unit: "whole", category: "Produce" },
      { name: "Vegetable broth", amount: 500, unit: "ml", category: "Pantry" },
      { name: "Fresh basil", amount: 20, unit: "g", category: "Produce" },
      { name: "Heavy cream", amount: 100, unit: "ml", category: "Dairy" },
      { name: "Olive oil", amount: 3, unit: "tbsp", category: "Pantry" },
    ],
    steps: [
      "Halve tomatoes, roast with onion and garlic at 200°C for 40 minutes",
      "Blend roasted vegetables with broth",
      "Add cream, simmer 5 minutes",
      "Blend basil with olive oil for basil oil",
      "Serve topped with basil oil",
    ],
    nutrition: { calories: 220, protein: 4, carbs: 18, fat: 14 },
  },
  {
    id: "r052",
    name: "Poached Eggs on Greens",
    description: "Soft poached eggs on a bed of sautéed kale, white beans, and lemon",
    servings: 2,
    prepTime: 5,
    cookTime: 12,
    tags: ["Vegetarian", "Keto", "Gluten-Free", "High-Protein"],
    ingredients: [
      { name: "Eggs", amount: 4, unit: "large", category: "Protein" },
      { name: "Kale", amount: 200, unit: "g", category: "Produce" },
      { name: "Cannellini beans", amount: 200, unit: "g", category: "Protein" },
      { name: "Garlic cloves", amount: 3, unit: "whole", category: "Produce" },
      { name: "Lemon", amount: 1, unit: "whole", category: "Produce" },
      { name: "Olive oil", amount: 2, unit: "tbsp", category: "Pantry" },
      { name: "Parmesan cheese", amount: 30, unit: "g", category: "Dairy" },
    ],
    steps: [
      "Sauté garlic in olive oil, add kale and cook 3 minutes",
      "Add beans, warm through",
      "Poach eggs in simmering water",
      "Plate greens, top with poached eggs",
      "Squeeze lemon, shave parmesan",
    ],
    nutrition: { calories: 360, protein: 26, carbs: 20, fat: 20 },
  },
];

export function getRecipeById(id: string): Recipe | undefined {
  return BUILT_IN_RECIPES.find((r) => r.id === id);
}
