"""Safety utilities: log redaction, prompt-injection sanitization, ID validation.

This module is intentionally lightweight — it exists to harden a few hot paths
where Trinity pulls attacker-influenced data into privileged contexts
(system prompts, logs, filesystem IDs).
"""
from __future__ import annotations

import logging
import re
from typing import Pattern


# ── Secret redaction ──────────────────────────────────────────────────

# Order matters: more-specific prefixes are matched first so the generic
# "sk-..." pattern doesn't gobble longer keys before they're labelled.
_REDACT_PATTERNS: list[tuple[Pattern[str], str]] = [
    (re.compile(r"sk-ant-[A-Za-z0-9_-]{20,}"), "sk-ant-***"),
    (re.compile(r"sk-proj-[A-Za-z0-9_-]{20,}"), "sk-proj-***"),
    (re.compile(r"sk-or-[A-Za-z0-9_-]{20,}"), "sk-or-***"),
    (re.compile(r"\bsk-[A-Za-z0-9_-]{24,}\b"), "sk-***"),
    (re.compile(r"\brk_live_[A-Za-z0-9]{20,}\b"), "rk_live_***"),
    (re.compile(r"\bsk_live_[A-Za-z0-9]{20,}\b"), "sk_live_***"),
    (re.compile(r"\bpk_live_[A-Za-z0-9]{20,}\b"), "pk_live_***"),
    (re.compile(r"\bwhsec_[A-Za-z0-9]{20,}\b"), "whsec_***"),
    # Telegram bot token: <bot_id>:<35+ chars>
    (re.compile(r"\b\d{6,12}:AA[A-Za-z0-9_-]{30,}\b"), "<telegram_token>"),
    # GitHub personal / OAuth / app tokens
    (re.compile(r"\bgh[pousr]_[A-Za-z0-9]{30,}\b"), "gh*_***"),
    # AWS access key ID
    (re.compile(r"\bAKIA[0-9A-Z]{16}\b"), "AKIA***"),
    # Bearer tokens in HTTP-ish context
    (re.compile(r"(?i)\bBearer\s+[A-Za-z0-9\-_.=]{20,}"), "Bearer ***"),
    # PEM-encoded private keys
    (
        re.compile(
            r"-----BEGIN [A-Z ]*PRIVATE KEY-----[\s\S]+?-----END [A-Z ]*PRIVATE KEY-----"
        ),
        "<redacted PEM key>",
    ),
]


def redact(text: str) -> str:
    """Return ``text`` with known secret shapes masked."""
    if not text:
        return text
    for pattern, replacement in _REDACT_PATTERNS:
        text = pattern.sub(replacement, text)
    return text


class _RedactingFilter(logging.Filter):
    """Logging filter that rewrites the formatted record message."""

    def filter(self, record: logging.LogRecord) -> bool:
        try:
            msg = record.getMessage()
            redacted = redact(msg)
            if redacted != msg:
                record.msg = redacted
                record.args = ()
        except Exception:
            pass
        return True


def install_redaction_filter(logger: logging.Logger | None = None) -> None:
    """Attach the redaction filter to a logger (root by default).

    Idempotent — safe to call more than once.
    """
    target = logger if logger is not None else logging.getLogger()
    if not any(isinstance(f, _RedactingFilter) for f in target.filters):
        target.addFilter(_RedactingFilter())
    for handler in target.handlers:
        if not any(isinstance(f, _RedactingFilter) for f in handler.filters):
            handler.addFilter(_RedactingFilter())


# ── Prompt-injection hardening ────────────────────────────────────────

# Any content that will be embedded inside <active_memory>…</active_memory>
# blocks must not be able to close the tag and emit a new instruction.
_CLOSE_TAG_RE = re.compile(r"</\s*active_memory\s*>", re.IGNORECASE)
_OPEN_TAG_RE = re.compile(r"<\s*active_memory\b[^>]*>", re.IGNORECASE)
_CONTROL_CHARS_RE = re.compile(r"[\x00-\x08\x0b\x0c\x0e-\x1f\x7f]")


def sanitize_for_prompt(text: str, *, max_chars: int = 2000) -> str:
    """Strip control chars and neutralize tag injections before embedding.

    Memory content is attacker-influenceable (users can dictate memories the
    agent then recalls). This function makes it safe to splice such content
    into a system prompt tagged block.
    """
    if not text:
        return text
    text = _CONTROL_CHARS_RE.sub("", text)
    text = _CLOSE_TAG_RE.sub("</active_memory_escaped>", text)
    text = _OPEN_TAG_RE.sub("<active_memory_escaped>", text)
    if len(text) > max_chars:
        text = text[:max_chars] + "…[truncated]"
    return text


# ── Memory ID validation ──────────────────────────────────────────────

# IDs generated by _next_id() look like mem_20260413_001.
# Migrated IDs (e.g. from OpenClaw) use a letter+digit suffix like mem_20260414_g01.
# Anything outside this shape is a path-traversal attempt.
_MEMORY_ID_RE = re.compile(r"^mem_\d{8}_[A-Za-z0-9]{1,16}$")


def is_valid_memory_id(memory_id: str) -> bool:
    """Return True if ``memory_id`` matches the canonical shape."""
    return bool(memory_id) and bool(_MEMORY_ID_RE.match(memory_id))


def validate_memory_id(memory_id: str) -> None:
    """Raise ValueError if ``memory_id`` is not canonically shaped."""
    if not is_valid_memory_id(memory_id):
        raise ValueError(f"Invalid memory ID: {memory_id!r}")
